//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "moves")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: String,
    pub book_id: Option<String>,
    pub fen: String,
    pub is_me: bool,
    pub parent: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub mov: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
